meta init
dsp-work/mtst_lib pull request #2
Opened 2021-10-27 07:46 UTC by name1204

2021-11-15 13:19 UTC, chatblanc-ciel requested changes

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +#include "./opt_helper.hpp"
メタ手法だから、他の余計なものへの依存はつくらないようにする

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +struct Harmony_Search_Parameter
```suggestion
struct HarmonySearchParameter
```

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +    double R_p;       //値調整比率(大きければ大きい程、値を調整する確率が上がる)
```suggestion
    //ハーモニーサーチのパラメータ
    size_t max_iter;   //更新回数
    size_t harmony_size; //ハーモニーメモリのサイズ
    double band_width; //バンド幅
    double R_a;       //選択比率(大きければ大きい程、ハーモニーメモリ内が使われる)
    double R_p;       //値調整比率(大きければ大きい程、値を調整する確率が上がる)
```

R_a, R_pはなんか名前変えたいよね
単文字は嫌だ

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +    vector<double> Harmony;
```suggestion
    vector<double> harmony;
```

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +struct Harmony_Search_Strategy
```suggestion
struct HarmonySearchStrategy
```

2021-11-15 13:19 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +    FilterParam fparam;
これは`HarmonySerachOptimizer`に持たせたいやーつ
```suggestion
    Harmony_Search_Parameter Hparam;

    Result optimize();
```

2021-11-19 08:19 UTC, name1204 commented on lib/HM/Harmony_Search.hpp
> +#include "./opt_helper.hpp"
そしたらfparamやResult型のoptimaizeはどうなるのでしょうか

2021-11-20 10:20 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +#include "./opt_helper.hpp"
`Result`はともかく、fparamはメタを使う人が選ぶもの(導入するもの)なので
検証用のプログラムで定義します。
メタ側では使いません(存在しません

2021-11-25 13:06 UTC, name1204 commented
requestが押せなくなっているためコメントで通知を送ります。コードの確認お願いします。

2021-11-26 07:52 UTC, chatblanc-ciel requested changes
なぞ

2021-11-26 07:52 UTC, chatblanc-ciel commented on lib/HM/Harmony_Search.hpp
> +#ifndef LIB_HARMONY_SEARCH_HPP_
なぞ

2021-12-03 05:40 UTC, closed without merging